# Generated by Django 5.0.6 on 2024-05-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('inquiry', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('advertising', 'Advertising'), ('editorial', 'Editorial'), ('mg', "Men's Grooming"), ('rs', 'Runaway Show'), ('ws', 'Wig Styling')], max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(default='no-image.jpg', upload_to='gallery')),
            ],
            options={
                'db_table': 'gallery',
            },
        ),
    ]
